lam:
  build: ./lam
  ports: 
    - 8080:8080
  volumes:
    - ./lam:/go/src/github.com/amku91/lam/api
  links:
    - database

database:
  container_name: lammongo
  image: mongo:3.0
  ports:
      - "27017:27017"
  environment:
      - DB_NAME=lam
      - DB_ROOT_USERNAME=admin
      - DB_ROOT_PASSWORD=admin123
  restart: on-failure
  volumes:
      - ./data:/db
  command: mongod -u admin -p admin123 --authenticationDatabase lam --smallfiles --quiet --logpath=/dev/null

  #--sslDisabledProtocols=TLS1_1 --sslMode=allowSSL MONGO_INIT --quiet